# Generated by Django 4.1.7 on 2023-02-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipestep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['step_number']},
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='order',
        ),
        migrations.AddField(
            model_name='recipestep',
            name='step_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
